# Generated by Django 3.2.8 on 2021-12-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_info', models.TextField()),
                ('property_info', models.TextField()),
                ('around_info', models.TextField()),
                ('family_info', models.TextField()),
                ('friends_info', models.TextField()),
                ('pets_info', models.TextField()),
                ('medical_info', models.TextField()),
                ('inherit_info', models.TextField()),
                ('contact_info', models.TextField()),
                ('message_info', models.TextField()),
            ],
        ),
    ]
