# Generated by Django 3.2.8 on 2022-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ending', '0002_ending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ending',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
